### ISSUE TITLE
CloseButton no longer working.

### ISSUE THREAD

**Issue by beetlegigg** [peterhinch/micropython-touch#12]
Hi Peter
A day or two back I built a mp for the rpi picoW using what I think is a version of the V1.24 preview ( I download the mp by using  git clone https://github.com/micropython/micropython.git --branch master.   I froze in the mp-touch and the mqtt_as by adding the latest files copied from your repository to the manifest.   (as I had previously done a couple of months ago)

All seems to work OK except the CloseButton will not close the program.   It will, as before, close a sub screen and return to the base screen, but when the CloseButton is clicked on the base screen everything comes to a halt but I don't get back to the REPL prompts as I used to.  (running from Thonny) The only recourse is to power cycle the picoW.

I have the previous build so I can revert so its not a pressing issue, but I was wondering if you have any idea of what may be amiss or the best way to track this down.
Thanks.

**Comment by peterhinch** [comment]
Please could you try one of the demo scripts to determine whether the close button works correctly (e.g. [simple.py](https://github.com/peterhinch/micropython-touch/blob/master/gui/demos/simple.py)).

I have had problems with the close button not responding to touch, but that doesn't sound like what's happening in your case: it sounds as if it's responding but not behaving correctly.

Just FYI, causes resulted from the small size of the button and its location at the extreme limits of the screen:
* Imprecise calibration of the touch overlay.
* Inaccurate touches (fixed by using a stylus).
